### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by 3ripleM**
please squash the commits before merging

thanks

### CODE REVIEW

**Comment by hosseinfani** [comment]
@3ripleM 
the pr doesn't have changes to the requirement.txt and environment.yml. is that ok?

**Comment by 3ripleM** [comment]
Actually thats on another branch, since I'm not able to run on conda environment because there are some conflicts in packages that I will try to resolve and then I make that PR; meanwhile, I'm working on CI to test how can we achieve multi-stage build + test.

**Comment by hosseinfani** [comment]
@3ripleM 
thank you.

**Comment by 3ripleM** [comment]
@hosseinfani 
Oh, it wasn't running properly. I couldn't resolve the issue we had on the toy dataset, but I'm working on it, so it will be done soon. I've also configured the lab computer you assigned to me to test the Docker version with GPU.

**Pull request merged**
